
const transcriptions = [
    {
        transcription: "para muita gente é fácil mas muita gente\ntambém tem dificuldade nessa arte do dia\na dia do brasileiro o ingrediente\nnutritivo que está na nossa mesa do dia\na dia se passar um pouco do ponto e fica\npágina escura se você tirar ele antes do\ntempo ele fica com a gema mole então\nhoje você vai saber o tempo certo a\nforma certa de deixar a gema gostosinha\nnutritiva e super gostosa eu sou ex\ngrande e claro receita fácil nem comigo\nnão tem mistério é só aqui na panela vai\ncolocar água o suficiente para cumprir\ntodos os seus ovos\nvou ligar o meu fogo em fogo médio\n[Música]\ne aí eu vou deixar essa água e\nesquentando por dois minutos antes da\ngente colocar os nossos jogos\n[Música]\ndois minutos depois com a nossa água já\nquem tinha eu vou começar a colocar meus\njogos aqui ou por outro eu vou preparar\nos seis jogos que eu estou comentando a\nminha dieta\naliás se você não está acompanhado estou\nfazendo blogs ainda dieta acompanha o\nnosso canal no youtube que eu estou\nfazendo vídeos de 30 vídeos das minhas\nrefeições fazem entrevistas a economia e\nda tecnologia está nutricionista todo\nmundo fica ligado que você 120 dias\nbacanas vão acompanhar a transformação\ndesse corpitcho aqui então depois que\nvocê foi o qual todos os jogos aqui na\npanela é o seguinte o truque é você\nesperar a água ferver a água começou a\nferver você vai contar no seu elogio e\n18 minutos do eln em sete minutos no e 9\n2010\nsão oito minutos exatos e vai estar\ntodos seus ovos\n[Música]\noito minutos depois os nossos ovos já\nestá pronto é garantido nunca maior sua\nvida você vai errado fazer esses ovos\nagora é só descartar essa água quente eu\ngosto de colocar água fria descartou\ntambém coloca outra água fria e deixe\nesfriar por dois minutos porque eu deixo\nesfriando porque quando a gente for\ndescascar\nele vai sair da casca facilmente você\nvai abrir vai ser todo dia quando você\ndiz cassel como o ovo quente ela fica\ngrudando da pele fica aquela dificuldade\npara sair à caça do rio preto até\nvontade de tomar café da manhã com isso\nacontece então de destruição desse ouro\ntenha paciência e quando tiver friozinho\nvocê vai lá descasca e vai ser\nfacilmente\n[Música]\n[Música]\ne é isso você viu como é fácil fazer\novos se quer aprender mais alguma dica\nbásica do dia a dia sem a fazer arroz\nfazer feijão fazer uma coisa que você tá\nacostumado dia a dia mas tem dificuldade\ncomenta que putin alegres aqui embaixo\nque você gostaria de aprender a fazer é\nque eu vou trazer com todo carinho para\nvocês vocês tenham gostado eu fico por\naqui até à próxima champions\n",
        questions: [
            ""
        ]
    }
]

export default transcriptions